monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

        # Le nom de la "channels" correspond au nom indiqué dans le fichier config/packages/routes/services.yaml
        # dans le path on indique le nom du fichier qui recevra toutes les infos concernant les mises à jour des status.
        # c'est dans la classe UpdateStateCommand que le fichier sera implémenté par la ligne  $this->log->info
        updatestate:
            type: stream
            path: "%kernel.logs_dir%/updatestate.log"
            level: debug
            channels: ["updatestate"]
